spring.datasource.url=jdbc:postgresql://localhost:5432/mamda_order
spring.datasource.username=postgres
spring.datasource.password=123sssSSS.
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=*

server.port=8082

