
spring.datasource.url=jdbc:postgresql://localhost:5432/mamda_order
spring.datasource.username=postgres
spring.datasource.password=123sssSSS.
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=*

server.port=0

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.catalogue-service.sliding-window-size= 5
resilience4j.circuitbreaker.instances.catalogue-service.failure-rate-threshold= 50
resilience4j.circuitbreaker.instances.catalogue-service.wait-duration-in-open-state= 10s
resilience4j.circuitbreaker.instances.catalogue-service.permitted-number-of-calls-in-half-open-state= 5
resilience4j.circuitbreaker.instances.catalogue-service.minimum-number-of-calls= 3
